version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
            - "443:443"
            - "9000:9000"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    mysql:
        image: mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=123456"
            - "MYSQL_DATABASE=root"
        ports:
            - "3306:3306"
    redis:
        image: redis
        ports:
            - "6379:6379"
